### ISSUE TITLE
Code ENOENT 

### ISSUE THREAD

**Issue by RaghavDabra** [IshaanOhri/Spreen#1]
npm not able to find files 

errno -4058

**Comment by IshaanOhri** [comment]
Could you please list down the steps to produce the error? Could you also let me know the OS you are using?

**Comment by RaghavDabra** [comment]
npm install was interrupted and unable to proceed installing required dependencies

I also tried using spreen on Kali and ubuntu and later on i thought maybe its some issue with the linux itself so i tried using Git 
Accoridng to me there is a corruption in the packages while the installation

So basically we need to install required packages.json and delete some nodes manually 

![Capture](https://user-images.githubusercontent.com/66009953/107727976-b648df00-6d12-11eb-8efd-94ad0799c374.JPG)

(I dont really have much knowledge regarding this and it was a new error for me as well and I searched about it )

**Comment by IshaanOhri** [comment]
Try these steps:

1. Delete `package-lock.json` and `node_modules`.
2. Clear npm cache by `npm cache clear --force`.
3. If you are using visual studio code, close it and try running `npm install` again.

Similar to https://github.com/npm/npm/issues/17444

**Comment by RaghavDabra** [comment]
Sure I'll try and let u know, Thank you

**Comment by IshaanOhri** [comment]
> Sure I'll try and let u know, Thank you

Where you able to try?
